### ISSUE TITLE
Link quality and signal streght stuck with linux kernel 4.0.4

### ISSUE THREAD

**Issue by LeleDev** [uoaerg/wavemon#10]
Link quality and signal strength values aren't updated on a time basis with the following linux kernel versions:
kernel-4.0.4-201
kernel-4.0.4-202

While everything works just fine on the older one:
kernel-3.19.7-200

I'm using fedora 21, 64bit

**Comment by grrtrr** [comment]
I have just confirmed this by upgrading to 4.1.0-rc6, using Dave Miller's net-tree. It looks like a bug in the 80211 wireless system. wavemon, like wireless-tools, uses the old wireless-extensions ioctl interface. What needs to be done next is to report a bug to the Linux wireless developers. I will see what kind of details I can get hold of. If you have the time and want to go ahead, please feel welcome to submit a bug report https://wireless.wiki.kernel.org/ if I am not able to respond quickly enough. Thanks for reporting this.

**Comment by LeleDev** [comment]
Mmh, if it is a wireless-tools problem, why if I press f3 data gets updated realtime instead? if it works in 'f3' mode isn't supposed to work also elsewhere?

**Comment by grrtrr** [comment]
Thanks to Johannes Berg, this has just been fixed: https://bugzilla.kernel.org/show_bug.cgi?id=99691

He provided a patch that restores the behaviour. Thanks again for reporting the issue.

**Comment by LeleDev** [comment]
Thank you for support!
