### ISSUE TITLE
Positive signal level

### ISSUE THREAD

**Issue by slaigai** [uoaerg/wavemon#100]
Positive signal level causing histogram (among other things) to fail but `avg sig` in the Info section properly shows negative values 

![image](https://user-images.githubusercontent.com/45932206/109932011-7ffde000-7c7e-11eb-9dbe-508f9538780b.png)

![image](https://user-images.githubusercontent.com/45932206/109932342-e97dee80-7c7e-11eb-9c81-fa67c92ff87d.png)

**Comment by grrtrr** [comment]
Hi thanks for reporting. This looks like an _overflow_ (some values are mapped from 0..255). 
Do you get the same in the F2 / History Screen?

If not, can you help debug the issue by subsequently commenting out the 3 possible sources for `sig_level` in `info_scr.c`?
```c
// info_screen.c:display_levels()

// ...
        sig_level = ls_cur->signal;                       // First possible source

        /* See comments in iw_cache_update */
        if (sig_level == 0)
                sig_level = ls_cur->signal_avg;           // Second possible source
        if (sig_level == 0)
                sig_level = ls_cur->bss_signal;           // Third possible source
```

**Comment by slaigai** [comment]
Yup, same thing on the history screen. No traces are shown here due to the signal value being out of range

![image](https://user-images.githubusercontent.com/45932206/110004721-9894e700-7ccc-11eb-9e25-af417d9b492a.png)

**Comment by grrtrr** [comment]
I see -- `lhist_screen.c` actually has the same `if/else` statement as above:
1. first try `ls->signal`,
2. then `ls->signal_avg`,
3. finally `ls->bss_signal`.
What you showed above (the _correct_ level under `beacons`) is yet another variable - `beacon_avg_sig`.

The first two (signal, signa_avg) are casts to `int8_t`, the last is a cast to `int`.
I will look into this later today or tomorrow.

**Comment by grrtrr** [comment]
So here is an update - it looks very similar to #47 , where a driver reported a positive average value.

Can you please share the output of
  - `iw dev <yourDevName> station dump`
  - `iw dev <yourDevName> link`

Card type / driver may also be helpful - this could be a driver issue, perhaps there is already a fix for that.

**Comment by grrtrr** [comment]
@slaigai - when you have time, could you please run `iw` to confirm which of the 3 levels is causing troubles?

On Debian / ubuntu it can be installed via `apt-get -y install iw`. Or you can build it from source [here](https://wireless.wiki.kernel.org/en/users/documentation/iw).

I will be adding a fix that _flips the sign_ of positive signal levels, but would like to double-check, since
in #47 one of the levels was completely off (by +112dB).

**Comment by grrtrr** [comment]
@slaigai - to help me fix this, could you please share the output of

- `iw dev <yourDevName> station dump`
- `iw dev <yourDevName> link`

With that information, I should have a fix ready shortly. Thank you.
