### ISSUE TITLE
\xf0\x9f\x87\xb9\xf0\x9f\x87\xb7 chars in F3 Scan List

### ISSUE THREAD

**Issue by asansli** [uoaerg/wavemon#102]
Thanks for such a great work!

Any way to show emoticons as it is, not like it's special chars.

Below image shows special chars used for this access point 🇹🇷 > \xf0\x9f\x87\xb9\xf0\x9f\x87\xb7
![image](https://user-images.githubusercontent.com/1895377/116797137-fab27280-aaea-11eb-831f-de2979e180e2.png)

**Comment by grrtrr** [comment]
Hi, sorry for the late reply.

This may be possible, the question is if it would render well in all situations. On my terminal it just prints "[T][R]" (emojicon):
![image](https://user-images.githubusercontent.com/5132989/117882984-e0aa2a00-b278-11eb-9243-68f61185b7bc.png)

**Comment by petrkutalek** [comment]
@grrtrr You are right, it looks the same on my system. (Yes, it has unicode support with no issues.)

![screenshot_20210612_153654_cutout](https://user-images.githubusercontent.com/42769564/121777806-359cd100-cb94-11eb-98cd-0a5f7aaa4b65.png)

**Comment by grrtrr** [comment]
I decided to not add support for this.
