### ISSUE TITLE
wavemon does not work with interface in a bond

### ISSUE THREAD

**Issue by petrkutalek** [uoaerg/wavemon#103]
If the wireless device is in a bond, wavemon erroneously reports that _the interface is blocked by software RF-kill_ and does not display some data. Signal quality information and network scan tab work fine though.

![screenshot_20210611_210901_cutout](https://user-images.githubusercontent.com/42769564/121737993-e7d38a80-caf9-11eb-80ee-6434a0f7e686.png)

**Comment by grrtrr** [comment]
Can you please provide the outputs of
- `sudo rfkill list` and
- `ip link show`?

**Comment by petrkutalek** [comment]
Of course I can, I'd love to. Thank you for your time.

```
kernel: iwlwifi 0000:00:14.3: Detected Intel(R) Wireless-AC 9560 160MHz, REV=0x318

$ wavemon -v
wavemon 0.9.3
Distributed under the terms of the GPLv3.

$ cat /etc/os-release
NAME="Arch Linux"
...
```

```
$ sudo rfkill list
0: tpacpi_bluetooth_sw: Bluetooth
	Soft blocked: no
	Hard blocked: no
1: tpacpi_wwan_sw: Wireless WAN
	Soft blocked: yes
	Hard blocked: no
2: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
3: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
```

```
$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wwp0s20f0u7: <BROADCAST,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ██:██:██:██:██:██ brd ff:ff:ff:ff:ff:ff
3: wlp0s20f3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc noqueue master bond0 state UP mode DORMANT group default qlen 1000
    link/ether ██:██:██:██:██:██ brd ff:ff:ff:ff:ff:ff permaddr ██:██:██:██:██:██
4: enp0s31f6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ██:██:██:██:██:██ brd ff:ff:ff:ff:ff:ff
5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ██:██:██:██:██:██ brd ff:ff:ff:ff:ff:ff
```

```

**Comment by grrtrr** [comment]
@petrkutalek - I just made a change on `master`. Would you be able to _test this_, and also see if it addresses the misleading `rfkill` information?

**Comment by petrkutalek** [comment]
😀 Thank you!! Great! Can you share what the problem was?

![screenshot_20210613_131654_cutout](https://user-images.githubusercontent.com/42769564/121805166-43149280-cc4a-11eb-8c4a-2380f0fee3d4.png)

**Comment by grrtrr** [comment]
Hi thanks for testing. The details are all in the commit. Is this still having issues with rfkill, or can this issue be closed?

**Comment by petrkutalek** [comment]
Everything works perfectly, this issue can be closed. Thank you, good work.
