### ISSUE TITLE
Switch from 0.8.2 to 0.9.3: inconsistent display of packet counts

### ISSUE THREAD

**Issue by Nordilf** [uoaerg/wavemon#104]
Hi, i switch from 0.8.2 to 0.9.3. When the RX packet count goes over 1GiB that happend.
![wavemon rx-count](https://user-images.githubusercontent.com/6377461/126894921-0f9785a4-5be1-4546-8c10-df4a483900ec.png)
 doesnt have this behavior with 0.8.2

Ty for your work

**Comment by grrtrr** [comment]
Hi, thanks for reporting.

Can you please try compiling from `master`? I think this is solved in 2a22c3da.

**Comment by Nordilf** [comment]
hi,
 i`ve tried without of luck. First purge the old one, purge all dependencies, restart, and do it twice again from scratch.

**Comment by grrtrr** [comment]
Ok, so is that a _build problem_? Usually it works as
```bash
./configure && make && ./wavemon
```

**Comment by Nordilf** [comment]
<pre><font color="#8AE234"><b>projekt42@projekt42</b></font>:<font color="#739FCF"><b>~/Downloads/wavemon-0.9.3</b></font>$ ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking net/if_arp.h usability... yes
checking net/if_arp.h presence... yes
checking for net/if_arp.h... yes
checking netinet/ether.h usability... yes
checking netinet/ether.h presence... yes
checking for netinet/ether.h... yes
checking net/ethernet.h usability... yes
checking net/ethernet.h presence... yes
checking for net/ethernet.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking ncursesw/curses.h usability... yes
checking ncursesw/curses.h presence... yes
checking for ncursesw/curses.h... yes
checking for sys/socket.h... yes
checking for linux/if.h... yes
checking for linux/wireless.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for pow in -lm... yes
checking for waddstr in -lncursesw... yes
checking for pthread_create in -lpthread... yes
checking for cap_get_flag in -lcap... no
checking for gettimeofday... yes
checking for ether_ntohost... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNL3_GENL... yes
checking whether gcc needs -traditional... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
configure: creating ./config.status
config.status: creating Makefile</pre>

<pre><font color="#8AE234"><b>projekt42@projekt42</b></font>:<font color="#739FCF"><b>~/Downloads/wavemon-0.9.3</b></font>$ make V=1
 CC   about_scr.c
 CC   conf.c
 CC   conf_scr.c
 CC   error.c
 CC   help_scr.c
 CC   info_scr.c
 CC   iw_if.c
<b>iw_if.c:</b> In function ‘<b>iw_get_interface_list</b>’:
<b>iw_if.c:157:38:</b> <font color="#AD7FA8"><b>warning: </b></font>‘<b>%s</b>’ directive output may be truncated writing up to 8191 bytes into a region of size 16 [<font color="#AD7FA8"><b>-Wformat-truncation=</b></font>]
  157 |    snprintf(wrq.ifr_name, IFNAMSIZ, &quot;<font color="#AD7FA8"><b>%s</b></font>&quot;, p);
      |                                      <font color="#AD7FA8"><b>^~</b></font>
In file included from <b>/usr/include/stdio.h:867</b>,
                 from <b>wavemon.h:19</b>,
                 from <b>iw_if.h:19</b>,
                 from <b>iw_if.c:19</b>:
<b>/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10:</b> <font color="#34E2E2"><b>note: </b></font>‘<b>__builtin_snprintf</b>’ output between 1 and 8192 bytes into a destination of size 16
   67 |   return <font color="#34E2E2"><b>__builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,</b></font>
      |          <font color="#34E2E2"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
   68 | <font color="#34E2E2"><b>       __bos (__s), __fmt, __va_arg_pack ())</b></font>;
      |        <font color="#34E2E2"><b>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
 CC   iw_nl80211.c
 CC   iw_scan.c
 CC   lhist_scr.c
 CC   llist.c
 CC   rfkill.c
 CC   scan_scr.c
 CC   ui.c
 CC   utils.c
cc -O2 -Wall -pthread -I/usr/include/libnl3    wavemon.c about_scr.o conf.o conf_scr.o error.o help_scr.o info_scr.o iw_if.o iw_nl80211.o iw_scan.o lhist_scr.o llist.o rfkill.o scan_scr.o ui.o utils.o  -lncursesw -lm  -lnl-genl-3 -lnl-3 -lnl-3 -o wavemon
</pre>

<pre><font color="#8AE234"><b>projekt42@projekt42</b></font>:<font color="#739FCF"><b>~/Downloads/wavemon-0.9.3</b></font>$ sudo make install-suid-root
[sudo] Passwort für projekt42:       
/usr/bin/install -c -m 0755 -d /usr/local/bin
/usr/bin/install -c -m 4755 wavemon /usr/local/bin</pre>

 maybe it is helpfull
Greetz

**Comment by grrtrr** [comment]
This is still `0.9.3`, which does not have the fix. Can you please use `master`, under the `"Code"` button, there is an option to download a `.zip` file:
![image](https://user-images.githubusercontent.com/5132989/127325156-6d0fcf5a-5225-4c18-a657-67acb955fbcb.png)

**Comment by Nordilf** [comment]
Hi, done. 
Works like a charm. Ty for your patience and the work.
