### ISSUE TITLE
New feature request: Log listed SSID in search mode

### ISSUE THREAD

**Issue by inforza** [uoaerg/wavemon#110]
Hi. First of all, excellent job!
Is it possible to add a functionality to log all the founded SSID at "search mode" (F3), with name, date/hour last seeing, etc?
Tks in advantage.

**Comment by grrtrr** [comment]
I am not sure I understand the question. Do you mean
- an update to the Scan Window, where for each SSID it tracks the _last time_ the SSID was seen; or
- a _separate log function_ that continuously logs SSIDs to `stdout` (outside of the Scan Window), with timestamps?

**Comment by inforza** [comment]
Hi Gerrit. I think the second option is a better choice, to continuously log. If possible. 
Manyt tks your reply.

**Comment by grrtrr** [comment]
The question came up before (#34, #98). This can be done using `iw`, running from a `bash` or `python` script.

**Comment by inforza** [comment]
Oh good! Now I found it. This is a good way. I'll check the topics. Thanks for your attention.
