### ISSUE TITLE
Feature request: Split rx/tx rate line

### ISSUE THREAD

**Issue by ea4eoz** [uoaerg/wavemon#114]
Hello!

I'm suggesting an small enhance: split the tx and rx rate lines.

In my case with my 802.11ac wireless, that line is something like this:

rx rate: 520.0 Mbit/s VHT-MCS 5 80MHz short GI VHT-NSS 2 (exp: 64.6 MB/s), tx rate: 702.0 Mbit/s VHT-MCS 8 80MHz VHT-NSS 2  

That line is too long and obligue you to use an extra wide terminal to see it. Splitting in rx rate and tx rate will be much more readable with normal size terminals, something like this:

rx rate: 520.0 Mbit/s VHT-MCS 5 80MHz short GI VHT-NSS 2 (exp: 64.6 MB/s)
tx rate: 702.0 Mbit/s VHT-MCS 8 80MHz VHT-NSS 2  

In this way it is much easier to spot the differences between tx and rx. Adding the expected throughput in tx would be nice also.

Thanks in advance.

**Comment by grrtrr** [comment]
Are you able to compile from `master`? Else you could use [0.9.4](https://github.com/uoaerg/wavemon/releases/tag/v0.9.4).
It looks like this, which I think is what you are asking for:
![image](https://user-images.githubusercontent.com/5132989/185694896-259c9629-3204-4d71-b5fe-bc1ce255be5f.png)

**Comment by ea4eoz** [comment]
Hello!

That's exactly what I was asking for. I'm currently running version 0.9.1-1 (Debian unstable) so I guess I must wait a bit for that version reaching Debian.

Thank you
