### ISSUE TITLE
no supported... but iw dev, iw list, /proc/net/dev will show wlp1s0 and wlp2s0, WiFi works

### ISSUE THREAD

**Issue by bmalnersic** [uoaerg/wavemon#115]
McDebian on Linksys WRT1900ACSv2. No issues with AP, both 2,4GHz and 5GHz work. However wavemon will report "no supported wireless interfaces found!" even if adapters are listed when using 'iw dev', 'iw list' , 'hostapd_cli interface' and are listed under '/proc/net/dev'. e.g.:
```
# hostapd_cli interface
Selected interface 'wlp1s0'
Available interfaces:
wlp1s0
wlp2s0
```
What is the most probable reason? Any easy way to fix this?

**Comment by grrtrr** [comment]
Which version of `wavemon` is this (`wavemon -v` or F9 / 'a' key)?

**Comment by bmalnersic** [comment]
Oh, Debian repos... it is an old version, 0.8.2. Will build new version and another system and recheck:) Thank you for a very quick answer!!!

**Comment by bmalnersic** [comment]
Sure thing, after building 0.9.4 from source, it works! Thanks again!
