### ISSUE TITLE
Reduce CPU load?

### ISSUE THREAD

**Issue by ballo** [uoaerg/wavemon#12]
wavemon is great, but sometimes virtuoso-t uses quite a bit of CPU. I haven't yet been able to replicate this issue, but an option to change the polling rate may help.

wavemon itself uses 1.4% which doesn't sound like much unless you're on battery power.

**Comment by grrtrr** [comment]
Sorry without more details I can not answer much. What screen were you running (info screen, history screen, scan screen)?

Also, virtuoso-t is independent of wavemon. If it is a wavemon issue, it would occur regardless of virtuoso-t.

**Comment by grrtrr** [comment]
Is there any update on this, is there an issue with wavemon?

**Comment by ballo** [comment]
Oh, sorry, I went back to backtrack 5. Kali was frustrating so I just
backported what I needed.

**Comment by grrtrr** [comment]
I take it then that this is not something to be fixed in wavemon? If runtime on battery is important, it may make sense to use slower poll intervals; but I don't think it will make a huge change.

**Comment by ballo** [comment]
I think polling every half second ought to make a difference, but I don't
have a method to test that at the moment. If the issue arises again I'll
let you know

**Comment by grrtrr** [comment]
Haven't heard back in a while - closing this issue. If problem persists, please let me know.
