### ISSUE TITLE
Missing WEXT and /proc/net/wireless missing - wavemon error

### ISSUE THREAD

**Issue by justinian-tomegea** [uoaerg/wavemon#121]
Latest Openwrt 23.05 wavemon package is coming up with "no supported wireless interfaces found".

This is most likely because the kernel wireless extensions WEXT have been obsoleted. Since the graphical scanner behind Luci still works I am wondering if it is possible to switch wavemon.

Using rt2800usb with some panda pau wireless. The wifi adapter in RPI displays the same error.

**Comment by grrtrr** [comment]
Which `wavemon` version are you using? 

Dependency on `wext` was dropped in 83ff72b638b854b8582f06a41e30f52c486df38b.

If you are already using 0.9.4, can you use `iw` to see if it has similar problems?

**Comment by grrtrr** [comment]
Thanks for following up. I will tag a new release tonight, after work.

**Comment by grrtrr** [comment]
Just tagged [`v0.9.5`](https://github.com/uoaerg/wavemon/releases/tag/v0.9.5).
