### ISSUE TITLE
no supported wireless interfaces found!

### ISSUE THREAD

**Issue by Johnnie390** [uoaerg/wavemon#126]
Running Asahi Linux (Debian, kernel 6.9.4) on an an apple M2 Mini.
Wavemon has worked in the past, do not ask me when.
iw wlan0 scan is working, returning neighbouring AP/SSID's etc.
Running wavemon 0.9.1.

Anyone any bright ideas/tips?

TIA
J.

**Comment by grrtrr** [comment]
Please upgrade to `master` or 0.9.4 - `0.9.1` is from 2019 and there have been changes in how the wireless interfaces are detected since.
This may solve the problem.

**Comment by Johnnie390** [comment]
Thanks for the information. Will do and report back.

J.
