### ISSUE TITLE
Support for Wifi7 320MHz Channel widths not presenting?

### ISSUE THREAD

**Issue by chris4prez** [uoaerg/wavemon#128]
Hi this tool is fantastic but it looks like it is not able to present 320MHz channel widths for wifi7?

Excerpt of wavemon, see: (width: unknown)

├─Info──────────────────────────────────────────────────────────────────────────────────────────┤
│mode: Managed, connected to: 1A:05:C6:44:29:B9, time: 10:19m, inactive: 0.5s   		│
│freq: 6455 MHz, ctr1: 6425 MHz, channel: 291 (width: unknown), bands: 2			│
│beacons: 5870, avg sig: -45 dBm, interval: 0.1s, DTIM: 2                                       │
│rx rate: 3843.1 MBit/s                                                                         │
│tx rate: 3843.1 MBit/s 

Showing Width:
iw wlp9s0f0 info | grep 'channel'
	channel 101 (6455 MHz), width: 320 MHz, center1: 6425 MHz

**Comment by grrtrr** [comment]
@chris4prez - I updated the supported routines. Could you try building from `master` to see if that resolves the problem?

If not, please feel free to re-open issue.
