### ISSUE TITLE
wavemon: no supported wireless interfaces found! Check manpage for help.

### ISSUE THREAD

**Issue by olive-33** [uoaerg/wavemon#130]
Hello,

I backported "backport-iwlwifi.git" to an intel ax101 card. Now the sudo wavemon command gives me the message: "no supported wireless interfaces found! Check manpage for help."

sudo dmesg | grep -i wifi
[    3.557244] Loading modules backported from iwlwifi
[    3.557249] iwlwifi-stack-public:master:12220:5e893e52
[    3.743469] Intel(R) Wireless WiFi driver for Linux
[    3.743576] iwlwifi 0000:00:14.3: enabling device (0000 -> 0002)
[    3.746639] iwlwifi 0000:00:14.3: Detected crf-id 0x501, cnv-id 0x80400 wfpm id 0x80000030
[    3.746681] iwlwifi 0000:00:14.3: PCI dev 54f0/0244, rev=0x370, rfid=0x10c000
[    3.746684] iwlwifi 0000:00:14.3: Detected Intel(R) Wi-Fi 6 AX101
[    3.759394] iwlwifi 0000:00:14.3: TLV_FW_FSEQ_VERSION: FSEQ Version: 0.0.2.42
[    3.760365] iwlwifi 0000:00:14.3: loaded firmware version 89.6b44fa0b.0 so-a0-hr-b0-89.ucode op_mode iwlmvm
[    4.676949] iwlwifi 0000:00:14.3: WFPM_UMAC_PD_NOTIFICATION: 0x20
[    4.676999] iwlwifi 0000:00:14.3: WFPM_LMAC2_PD_NOTIFICATION: 0x1f
[    4.677009] iwlwifi 0000:00:14.3: WFPM_AUTH_KEY_0: 0x90
[    4.677018] iwlwifi 0000:00:14.3: CNVI_SCU_SEQ_DATA_DW9: 0x10
[    4.677100] iwlwifi 0000:00:14.3: Detected RF HR1 B3, rfid=0x10c000
[    4.717525] iwlwifi 0000:00:14.3: base HW address: 74:13:ea:4e:1e:48
[    4.739145] iwlwifi 0000:00:14.3 wlp0s20f3: renamed from wlan0
[    6.292988] iwlwifi 0000:00:14.3: WFPM_UMAC_PD_NOTIFICATION: 0x20
[    6.293036] iwlwifi 0000:00:14.3: WFPM_LMAC2_PD_NOTIFICATION: 0x1f
[    6.293045] iwlwifi 0000:00:14.3: WFPM_AUTH_KEY_0: 0x90
[    6.293054] iwlwifi 0000:00:14.3: CNVI_SCU_SEQ_DATA_DW9: 0x10
[    6.339237] iwlwifi 0000:00:14.3: Registered PHC clock: iwlwifi-PTP, with index: 0

iwconfig
lo        no wireless extensions.

enp1s0    no wireless extensions.

enp2s0    no wireless extensions.

wlp0s20f3  no wireless extensions.

vmnet1    no wireless extensions.

vmnet8    no wireless extensions.

cat /proc/net/wireless
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22

iw dev
phy#0
	Unnamed/non-netdev interface
		wdev 0x2
		addr 74:13:ea:4e:1e:49
		type P2P-device
	Interface wlp0s20f3
		ifindex 4
		wdev 0x1
		addr 74:13:ea:4e:1e:48
		type managed
		channel 48 (5240 MHz), width: 80 MHz, center1: 5210 MHz
		txpower 22.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0
lspci -k | grep -A 3 -i network
00:14.3 Network controller: Intel Corporation CNVi: Wi-Fi
	Subsystem: Intel Corporation Wi-Fi 6 AX101NGW
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi

**Comment by grrtrr** [comment]
Which version (`wavemon -v`) are you using? If it is before `0.9.6`, does and upgrade or build from `master` help?

**Comment by olive-33** [comment]
Hello,
I confirm in version 0.9.1 it does not work:
wavemon -v
wavemon 0.9.1
Distributed under the terms of the GPLv3.

I just installed the git version 0.9.6 and everything works correctly:
wavemon - status monitor for wireless network devices version 0.9.6
thanks
