### ISSUE TITLE
manpage contains a probably outdated address for bug reporting

### ISSUE THREAD

**Issue by guntbert** [uoaerg/wavemon#19]
The README.md states
> Send bug reports, comments, and suggestions by opening an issue on github.

while in wavemon.1 I read
> .SH "REPORTING BUGS"
> Send bug reports and/or suggestions to Gerrit Renker <gerrit@erg.abdn.ac.uk>.

**Comment by grrtrr** [comment]
Good catch, thank you. Will update shortly.
