### ISSUE TITLE
CFLAGS passed to ./configure are ignored

### ISSUE THREAD

**Issue by rofl0r** [uoaerg/wavemon#2]
```
CFLAGS="-O0 -g3" ./configure
...
make
gcc -O2 -Wall -pthread ...
```
well behaving autoconf users (more than 90%) generally drop the hardcoded -O2 CFLAGS when the user passes his own CFLAGS.
this seems to be the default behaviour.

**Comment by grrtrr** [comment]
`CFLAGS` are ignored during configure, but you can export or set them when running `make`; the `Makefile` provides for this.

**Comment by rofl0r** [comment]
so if you do ```make CFLAGS=-ffoo``` you dont override actually required CFLAGS and break the build ? i wonder why wavemon can't just do it like everyone else...
