### ISSUE TITLE
Inconsistent Levels between wavemon 0.7.6-2 and github master (latest commit 62949b3)

### ISSUE THREAD

**Issue by bmegli** [uoaerg/wavemon#20]
Hi @grrtrr,

## Hardware & Software
Hardware: Edimax EW-7811Un (this is Realtek RTL8188CUS)
OS: Linux ev3dev 4.4.19-15-ev3dev-ev3

I belive that both  RaspberryPi and ev3dev use 3rd party driver for this device (instead of upstream), so maybe it is not playing well with cfg80211. Some more info:

https://github.com/ev3dev/ev3dev/issues/669

(I am aware that the github version uses nl80211 and the old one wext to read data from the kernel)

## Problem

I am getting incosistent levels, both of link quality and signal level between wavemon versions.

E.g - signal level -45 dBm (0.03 uW) vs 20 dBm (100.00 mW)  [new vs old version).
E.g. - link quality 93 (65/70) vs 100 (100/100)

I am running 2 versions simultuanusly in 2 ssh windows on a mobile robot.

Also iw reports the same value (-45 dBm). 

In both versions values change in reasonable way (that is - as I am getting far away from the AP the link quality and signal level drops)

**Comment by grrtrr** [comment]
Hi, thank you for the detailed notes. This very much seems to be a kernel issue:
* with nl80211 (`iw` and master branch) the values (-45 dBm) seem to be correct,
* the link quality is a proxy figure, yet 100% is rare and suspicious
* the wext values (20 dBm and 100 out of 100) are suspicious.

You said that `iw` values look correct. Could you double check to see what `iwconfig` reports (this is the older, wext-based interface)? Very likely it will report the same values.

If that is the case, it is a problem of how wext is supported in the driver. It seems nl80211 works with this driver, but the legacy wext interface does not -- almost the opposite of the `rt3573sta` driver issue reported in #13 (the driver supports wext, but not nl80211).

If it turns out to be a kernel issue, it should be passed on to the kernel module developers, or the Linux wireless mailing list.

**Comment by bmegli** [comment]
> Hi, thank you for the detailed notes

Thanks for the great utility.

@bmegli wrote
> In both versions values change in reasonable way (that is - as I am getting far away from the AP the link quality and signal level drops)
@grrtrr replied
> You said that iw values look correct. 

Oh, I meant that both the new and old version values behave reasonble even though they differ. Both drop values as the distance raises. It's difficult for me to tell which one is correct with respect to absolute value (for the signal level)

> Could you double check to see what iwconfig reports (this is the older, wext-based interface)? Very likely it will report the same values.

I will check iwconfig tommorow (the hardware is in a different location).

**Comment by bmegli** [comment]
> Could you double check to see what iwconfig reports (this is the older, wext-based interface)? Very likely it will report the same values.

Here you are.

Yes, they seem to match. The output for the signal level is somewhat different.

wavemon 0.7.6-2
``` bash
lqInterfaceqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
xwlan0 (IEEE 802.11bgn, WPA/WPA2),  ESSID: "ROBOT",  nick: "<WIFI@REALTEK>"            x
tqLevelsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
x                                                                                      x
xlink quality: 100%  (100/100)                                                         x
x======================================================================================x
x                                                                                      x
xsignal level: 20 dBm (100.00 mW)                                                      x
x======================================================================================x
x                                                                                      x
x                                                                                      x
tqStatisticsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
xRX: 22,211 (10.91 MiB), invalid: 0 nwid, 0 crypt, 0 frag, 0 misc                      x
xTX: 24,134 (4.36 MiB), mac retries: 0, missed beacons: 0                              x
tqInfoqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
xmode: Managed,  access point: E4:F4:C6:41:F7:44,  sensitivity: 0/0                    x
xfreq: 2.437 GHz, channel: 6,  bitrate: 150 Mbit/s                                     x
xpower mgt: off                                                                        x
xretry: off,  RTS/cts: off,  Frag: off                                                 x
xencryption: no information available                                                  x
tqNetworkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
xmac: 80:1F:02:E6:93:32, ip: 192.168.0.101/24                                          x
mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
F1info  F2lhist F3scan  F4      F5      F6      F7prefs F8help  F9about F10quit
```

iwconfig
``` bash
root@ev3dev:~/wavemon# iwconfig wlan0
wlan0     IEEE 802.11bgn  ESSID:"ROBOT"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.437 GHz  Access Point: E4:F4:C6:41:F7:44
          Bit Rate:150 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****   Security mode:open
          Power Management:off
          Link Quality=100/100  Signal level=100/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

**Comment by grrtrr** [comment]
Thank you for checking this. It confirms that there is a problem with Wext, possibly the wext support in the wireless driver (otherwise the problem would be seen with other drivers, too). If it is possible for you, the best thing to do is to alert the driver maintainers to this problem.

Thank you also for the helpful other issues, I will look at them after work.

**Comment by bmegli** [comment]
Ok,

I am going to inform the driver maintainer when I find time.

I suppose nothing to be done here on the wavemon side then. Also thanks for sorting that out.
