### ISSUE TITLE
Some dependencies not listed in readme.md

### ISSUE THREAD

**Issue by bmegli** [uoaerg/wavemon#22]
I am reffering to github master (Latest commit 62949b3).

I think that I also needed for building: libncurses5-dev
I am certain that I also needed: pkg-config.

Without pkg-config at correct version wavemon configure complains with error message about libnl3 which is somewhat confusing (even though libnl3 is installed with the correct version)..

Maybe all of that is obvious from the configure output but it took me a while to figure out.

Kind regards!

btw - wavemon is great

**Comment by grrtrr** [comment]
Good suggestion, thank you. I will add that to the readme.
