### ISSUE TITLE
no supported wireless interfaces found!

### ISSUE THREAD

**Issue by davelister69** [uoaerg/wavemon#23]
I am running Kali 2 from a chromebook flip (ARMHF).

I have installed wavemon from both the kali repo and the git repository.

Both methods install/compile correctly, then when I run wavemon/wavemon -i wlan0 all I receive is:

no supported wireless interfaces found!

I have three separate ALFA cards that function fine with all the other tools I have tried (airodump-ng/kismet etc.) but for some reason wavemon doesn't detect them.

What is the best way to start debugging this issue?

Cheers,

Dave

**Comment by grrtrr** [comment]
The best places to look for are
* `/proc/net/dev` (this is what wavemon uses to check for wireless interfaces)
* `/proc/net/wireles` (if not there or empty, it is an indication that the driver does not support Wext wireless extensions)

Alternatively, can you try running the following:
* `iwconfig` - shows all (Wext-supported) wireless interfaces
* `iw dev` - modern variant, also displaying all wireless interfaces

**Comment by joerg-krause** [comment]
I 'm facing the same issue with latest master branch, commit affa6d8d18d8f52a6e2615cdc3c64c7ba50e96cd:

```
# wavemon -v
wavemon 0.8.0 with ncurses 5.9.20110404 and libnl 3.2.27.
Distributed under the terms of the GPLv3.
# wavemon -i wlan0
wavemon: no supported wireless interfaces found!. Check manpage for help.
# wavemon 
wavemon: no supported wireless interfaces found!. Check manpage for help.
# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:  265711    2899    0    0    0     0          0         0   265711    2899    0    0    0     0       0          0
  eth0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 wlan0:   41185     259    0    0    0     0          0        78    46411     210    0    0    0     0       0          0
```

**Comment by grrtrr** [comment]
The interface name `wlan0` appears in `/proc/net/dev`; the error that is produced by `wavemon` is caused by the `SIOGIWNAME` (an `ioctl` specific to wireless extensions) to fail on every interface in `/proc/net/dev`, including `wlan0`.

I am reopening this issue; my guess is that your `wlan0` interface does not (or not fully) support wireless extensions (can be verified by running `iwlist` or `cat /proc/net/wireless`.

I will therefore work on a different solution and get back shortly.

**Comment by joerg-krause** [comment]
You're right! I have not enabled wireless extensions for this test, but had the last time.

**Comment by grrtrr** [comment]
@joerg-krause - there is still some dependency of `wavemon` on wireless extensions; those calls would fail if this test ignores wirless extensions. 

The reason I stuck with this choice so long is that wireless extensions and libnl80211 do not offer the same set of features. Some features that wext provides are not in libnl80211.

**Comment by joerg-krause** [comment]
I see! However, I will re-run the test of the master branch with wext enabled later this week.

**Comment by grrtrr** [comment]
I have looked into this and decided to keep the check. The reason is that there is too much code which still depends on the wireless extensions. These calls would fail if the check were not done here. Deactivating calls that depend on wireless extensions would mean that only a part functions.
