### ISSUE TITLE
Supress list of ESSIDs?

### ISSUE THREAD

**Issue by thomaskien** [uoaerg/wavemon#24]
Hi there,

I just configured my raspi to display wavemon on the display after booting up - i am using the watterott-display http://www.watterott.com/de/RPi-Display - I know the display is too small, but it perfecly fits into a case built of an old nintendo gameboy ;-)

Is there  a way to ignore specific essids? would be great if our 93*4=372 devices of our infrastructure would be supressed ;-)

Regards from Aachen,

Thomas

**Comment by grrtrr** [comment]
Hi Thomas,

there is code which causes `wavemon` to adapt to (changing) screen size. This may or may not look good on a smaller display, but could be tweaked.

With regard to filtering out essids, an easy way would be a configuration file entry with a regular expression for the Scan Screen. Better would be a text box for editing on the configuration screen. 
Together with changing the Scan Screen, it is feasible but would take some work.

Gerrit
