### ISSUE TITLE
RX/TX rate is reported as MBit/s when it is KBit/s

### ISSUE THREAD

**Issue by 2m** [uoaerg/wavemon#31]
For slow RX/TX rate wavemon still reports rates as megabytes per second. Where it should be kilobytes instead.

**Comment by grrtrr** [comment]
Which one do you mean -- the one below:
![low_usage](https://cloud.githubusercontent.com/assets/5132989/21122512/c2972732-c08f-11e6-956e-736851aacd21.png)

This field is not a rate, it is just the number of bits transferred.

The 'Info' `tx rate` and `rx rate` are always in Mbits/sec. Or are you saying it is reported as 0?

**Comment by 2m** [comment]
![a](https://cloud.githubusercontent.com/assets/422086/21131377/4a6bed50-c149-11e6-919e-1650679f459c.png)

Hm. For some reason I have more info in the `Statistics` section.

**Comment by grrtrr** [comment]
Ah I see. The rate you are referring to is part of the channel survey data.
This particular bitrate is reported by the kernel in units of 100kBit/sec (`NL80211_RATE_INFO_BITRATE{,32}`). Hence it would not be useful to use a kbit resolution here.

**Comment by 2m** [comment]
Sure. But I think the displayed value is wrong. My connection is limited at 6Mbps, so it is impossible for the rate to be reported at 58Mbit/s.

**Comment by grrtrr** [comment]
It is a property of the wireless channel, not a throughput: see how [nl80211_put_sta_rate](http://lxr.free-electrons.com/source/net/wireless/nl80211.c?v=3.1#L2122) calculates the bitrate.

You will get identical output when running `iw dev wlp58s0 station dump`.

**Comment by grrtrr** [comment]
There is another rate sometimes reported, which is the _expected throughput_. Not all drivers support this, but it is closer to what one would expect.
