### ISSUE TITLE
Exporting signal strength data

### ISSUE THREAD

**Issue by lancebadoni** [uoaerg/wavemon#34]
I am wondering how collected signal strength data can be exported into, say, a csv file for later analysis.

I am using a RasPi 2 running Raspbian Jessie with Pixel.  My purpose in collecting _and_ storing strength data is to create a 3D heat map of Wi-Fi signal strength for 2.4GHz.

**Comment by grrtrr** [comment]
This has been requested earlier in #18. I still think wavemon is not the right tool for that.

_A better alternative_ is to use `iw` from e.g. a bash script, which could extract the data points into a CSV or column-format file; and could be run via a cronjob.

**Comment by engrasifkhan** [comment]
Hi, I also need the ame thing. Does iw has all the same stats offered by wavemon?
I also see on this [page](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=131849), that we can extract output using grep and sed. However its not working for me. It says that the (-d) option is not a valid option.

**Comment by grrtrr** [comment]
The `-d` option has been removed over 2 years ago, in dc81d8fd336adab35870a087852061a5668deb40. It seems that the raspberry PI page used an older version of wavemon.
You can probably achieve the same, if not better, results using `iw`. Have you looked into this?
