### ISSUE TITLE
[SOLVED] Wavemon "No Interface Data" on Intel AC-8260

### ISSUE THREAD

**Issue by smilemak** [uoaerg/wavemon#37]
Hi

I have to laptops with a similar configuration (both Arch Linux on Kernel 4.11.9-1-ARCH). Wavemon works flawlessly on one but not the other. Difference is mostly the hardware not the software setup. The not working model uses an Intel Dual-Band Wireless AC8260 card (the working one an Intel 7265 card).

I use wavemon 0.8.1-1 and the dependencies are installed. The kernel module for the WiFi card used is iwlwifi. An `iwlist <dev> scan` works flawlessly and also the WiFi works works fine. A `sudo wavemon` shows "NO INTERFACE DATA" on the info screen and nothing for vor Lhist but a Scan of the networks works fine.

Any ideas why this is?

**Comment by grrtrr** [comment]
This could be because of lacking support by the driver for nl80211. If that is the case you would not output from the `iw` command.

**Comment by smilemak** [comment]
That's an embarrassing one. I missed to connect to a WLAN prior to testing. Had this box atypically connected through LAN and therefore did not realize that. Sorry! And yes - `iw` works fine as well.
