### ISSUE TITLE
Signal bars and lines in terminal are messed up since latest ncurses update?

### ISSUE THREAD

**Issue by mr-blobbyyy** [uoaerg/wavemon#39]
This is my guess. I only use wavemon occasionally when adjusting my wifi dongle so I can't be sure. Same behaviour on sudo privileges.

My box: Antergos xfce, [wavemon 0.8.1-1](https://www.archlinux.org/packages/community/x86_64/wavemon/), [ncurses 6.0+20170902-1](https://www.archlinux.org/packages/core/x86_64/ncurses/) (updated a week ago.)

**Comment by rofl0r** [comment]
got a screenie showing what's wrong?

**Comment by grrtrr** [comment]
To determine whether this is an _ncurses_ problem, try any other application that relies on ncurses (on the Arch Linux [ncurses page](https://www.archlinux.org/packages/core/x86_64/ncurses/), many examples are listed, one example is [htop](https://www.archlinux.org/packages/extra/x86_64/htop/)).

If the other application(s) have the same problem, it would confirm that there is the same cause for terminal setup and libraries. It may still not be ncurses, it could also have to do with terminal setup.

**Comment by mr-blobbyyy** [comment]
Lines aren't fully drawn and bars aren't fully displayed but for the most part it is readable:
![Image](https://i.imgur.com/yCVEQMW.png)
...I forgot to mention the issue is still apparent when resizing the terminal window and waiting for elements to re-paint.

**htop** seems to be fine so this could be a gtk3 issue (depends vte3 & libxfce4ui->xfce4-terminal) since that's been updated recently as well.😐

**Comment by grrtrr** [comment]
Thanks for the picture. Resizing the window should normally clear it. To find out whether this is an X-window or X-terminal issue, could you run it from the native terminal (e.g. `/dev/tty1`, CTRL-Alt-F1)?

Another thing to test is how the histogram in `wavemon` is painted (F2, or `h`).

**Comment by mr-blobbyyy** [comment]
ctrl+alt+f1 dropped me to the tty terminal which killed my keyboard apparently so had to soft reboot.😐 
Decided to boot into "non-graphical" mode and wavemon is functioning perfectly there. I also found **xterm** in my list of applications and it's working in that terminal application as well.

xfce4-terminal histogram pic:
![image](https://i.imgur.com/g4t21Ax.png)
...no blue lines are painted horizontally compared with tty and the signal line is painted with dashes versus characters with tty. (**xterm** also paints dashes.)
'h' is help and apparently only paints "don't panic", assuming that's normal. 'l' is histogram. I also found out that the xfce terminal binds by default f1 and f10 to "online help" and "alt+f" -- but these binds can be disabled in its settings.

**Comment by grrtrr** [comment]
This confirms that the problem is with the xfce4-terminal. You might be able to get around it by setting `TERM=xterm` (or another terminal type that works), but I have no possibility of testing that here.

With regard to the histogram - this is as intended; the blue background (Signal/Noise Ratio) is not printed, since the driver does not report noise values (only a few drivers nowadays do this).

**Comment by grrtrr** [comment]
I haven't heard back. Closing issue since cause seems to be outside wavemon. Please inform the Arch Package maintainer(s); if there are any other problems, open a new issue.
