### ISSUE TITLE
release tarballs should be distributed on a proper download server

### ISSUE THREAD

**Issue by rofl0r** [uoaerg/wavemon#4]
there are some issues with github's "automatic tarball download"

- http is automatically redirected to https.
  this makes it impossible to download with non-https capable wget implementations like the one of busybox (note that statically linking against openssl usually involves ca 1.5 MB of binary bloat), used on embedded systems
- naming scheme: the tarball is named $TAG.tar.gz. in our case v0.7.6.tar.gz.
  the extracted directory otoh is named "wavemon-0.7.6".
  this requires special casing in buildtools that expect tarballs to extract into a directory of the same name as the tarball. it also makes it hard to identify which package dropped "v0.7.6.tar.gz" in the download folder, so one needs to unpack it to find out what it is. additionally there may be conflicts with other github projects that use the same tag name. for example if mpv happened to have a v0.7.6 release, that tarball would get the same name as the wavemon one and overwrite it.
- no choice of compression algorithm:
  instead of using a modern algorithm with good compression like xz, one is restricted to the decades old .gz algorithm which packs only about half as well
- generated configure scripts must live in the source repo so they end up in the tarball without forcing the user to have the entire autoconf stack installed.
usually git repos do not include configure scripts and all the files dropped from autoreconf runs (config.sub, m4 stuff, etc) which often exceed the size of the source code itself by far, and must be regenerated often, thus bloating the git repo. so packages usually have a make dist target which generates a release tarball including the autoconf stuff.

thus i recommend to use another download site for release tarballs, for example sourceforge.net (git repo can still stay here of course)

**Comment by grrtrr** [comment]
Closing this since all hosting is now on github.

**Comment by rofl0r** [comment]
bravo. i hope you read https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck/
