### ISSUE TITLE
Limiting the scan view to top X entries ?

### ISSUE THREAD

**Issue by rsyncnet** [uoaerg/wavemon#43]
Hello,

I wonder if it is possible for the scan view to be limited to the top 10 or top 20 most powerful access points ?

My environment has 55-75 APs in range, which are all seen by wavemon, but I wonder if I can limit that to the top 10 ?

Thank you.

**Comment by grrtrr** [comment]
Yes you can -- please set the 'Scan sort type' in the configuration screen (`sort_order` in wavemon.conf), which you can show by ascending/descending `signal` strength.
If you have more APs than fit on the screen (typical in urban places), it will show up as "hidden".
