### ISSUE TITLE
After quitting (F10), wavemon leaves the interface UP regardless of its original state

### ISSUE THREAD

**Issue by saviocmc** [uoaerg/wavemon#46]
**Current behavior:**
When I start wavemon and then go to the Scan window (F3) and my interface is DOWN, wavemon will set the interface state to UP with the message: "Interface *x* is down - setting it up..."
When I leave wavemon, the interface stays UP. In other words, wavemon does not set the interface state to DOWN when I leave it.

**Expected behavior:**
I would expect wavemon to set the interface back to its original state when I leave it.

I'm using wavemon in Arch Linux, installed from the ["community" official repository](https://www.archlinux.org/packages/community/x86_64/wavemon).
The current behavior cause me trouble because other software (e.g. [netctl](https://wiki.archlinux.org/index.php/Netctl)) expects the interface to be DOWN when I start them.
Today, as a workaround, a made a script to start wavemon that get the interface state before starting it and then when I quit wavemon, the script sets my interface back to its original state.

**Comment by grrtrr** [comment]
Hi, thanks for the report. 

Are you able to compile from `master`? I just added a change which should fix the problem. Please let me know if that works for you.

**Comment by saviocmc** [comment]
Hello.
Yes, I was able to compile from master and wavemon is now working exactly like I described above as what would be the expected behavior. If the interface is DOWN when I start wavemon, the interface is turned back to DOWN when I quit.

I compiled first from source and later from the Arch User Repository, [here](https://aur.archlinux.org/packages/wavemon-git/). It is working great in both cases. I'm sure that as soon as you release a new version (including the commit 4a160b1), the package in the Arch official repository will be updated as well. For now I'm gonna use the package from the user repository.

Thank you very much for your work.
wavemon is a tremendous tool and it is very useful to me in a daily basis.
Again, thanks for wavemon and for your readiness in solving this issue.

**Comment by grrtrr** [comment]
Thank you very much. Since [0.8.2](https://github.com/uoaerg/wavemon/tree/v0.8.2) just came out 6 weeks ago, I will probably wait a little. The Arch User Repository seems outdated, since it still points at the `eden-feed` link; I was unable to change that.

**Comment by saviocmc** [comment]
Hello again.
The AUR just holds [PKGBUILDs](https://wiki.archlinux.org/index.php/PKGBUILD). They are scripts to compile source code and package it as [pacman's](https://www.archlinux.org/pacman) packages. This is done in the user machine. The [Upstream URL field](https://wiki.archlinux.org/index.php/PKGBUILD#url) is indeed outdated, but it does not make any difference in the compiling process. If you see the whole script, [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wavemon-git), you will see that the [source field](https://wiki.archlinux.org/index.php/PKGBUILD#source) is pointing to the master branch here on github. The very goal of the existence of wavemon-git on AUR is to have the most possible updated software and still manage the package with pacman. As long as this repo exists with its current name, the script will work.

I can confirm that the package is up to date. I compiled wavemon using this AUR PKGBUILD script (and [yay](https://github.com/Jguer/yay)) and now I have the feature you introduced in the commit 4a160b1. When I run `wavemon -v` I got:
```
wavemon 0.8.2
Distributed under the terms of the GPLv3.
```
Nevertheless, I'm going to flag the script in AUR as out-of-date, so the maintainer can update the Upstream URL field.

Again, thank you very much for your work and for your attention to this issue.
