### ISSUE TITLE
SNR value

### ISSUE THREAD

**Issue by rafaelsilvag** [uoaerg/wavemon#49]
Dear
 
I'm trying to get SNR value for using in my projects. I've used Netlink library and I'm receiving cyclic values differently received by wavemon; 

root@node01:~# ./nl80211_info
Interface: ap1 | signal: -42 dB | noise: -56 | txrate: 104.0 MBit/s
Interface: ap1 | signal: -43 dB | noise: -82 | txrate: 104.0 MBit/s
Interface: ap1 | signal: -44 dB | noise: 125 | txrate: 104.0 MBit/s
Interface: ap1 | signal: -44 dB | noise: 99 | txrate: 104.0 MBit/s
Interface: ap1 | signal: -43 dB | noise: 73 | txrate: 104.0 MBit/s

My question is, how can I get the noise value and signal value to calculate the SNR as Wavemon uses? 

Regards,

**Comment by rafaelsilvag** [comment]
Thanks, @grrtrr for your quick reply!

I'm trying to get the noise using as follow:

typedef struct {
  int8_t noise;
} Wifi;
static struct nla_policy survey_policy[NL80211_SURVEY_INFO_MAX + 1] = {
        [NL80211_SURVEY_INFO_FREQUENCY]     = { .type = NLA_U32 },
        [NL80211_SURVEY_INFO_NOISE]         = { .type = NLA_U8 },
...

  if (sinfo[NL80211_SURVEY_INFO_NOISE]){
    ((Wifi*)arg)->noise = (int8_t)nla_get_u8(sinfo[NL80211_SURVEY_INFO_NOISE]);
  }
....
Wifi w;
printf("Interface: %s | signal: %d dB | noise: %.0f | txrate: %.1f MBit/s\n",
           w.ifname, w.signal, noise, (float)w.txrate/10)

Did you do other processes to get the correct noise value?

Regards,

**Comment by grrtrr** [comment]
@rafaelsilvag - any progress on this? Would like to close issue.
