### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by RoudiBoy** [uoaerg/wavemon#51]
Hi,

I don't know if I am in the right section, because I just need an information and I am not reporting an issue. If not, I am sorry.

I just wanted to know from where are coming the statistics information. I ran ifconfig but the values are not exactly the same as in the wavemon windows. In the wavemon windows, I also have 1 dropped packet and 2 failed packets, and when I ran ifconfig, I have 0 dropped, or erronned packets.

For information, I am using waveform as a real-time wireless monitoring (which is very usefull) and I want to log data too. But it seems like what I log is incorrect.

If you have any answers.

Thanks for the reading.

Sincerely

**Comment by grrtrr** [comment]
The `ifconfig` and `ip` (iproute2) programs only report statistics of the network interface.
These are generic stats (like txqueue and mtu) and have no knowledge of the underlying medium.

Wireless stats are reported in a different place and hence use other tools. An older tool is `iwconfig`, which is based on the wireless extensions. These have been in the Linux kernel for a long time (~20 years) but lag behind more recent developments.

Another drawback of the wireless extension was that they are based on ioctls. A more modern and scalable way of extracting stats from the live kernel is using [netlink](https://en.wikipedia.org/wiki/Netlink). 

This is what wavemon uses, and most of the code has been taken / adapted from [iw](https://wireless.wiki.kernel.org/en/users/documentation/iw). If you want to do continuous logging, that is the tool you should consider. wavemon is not set up to produce logs.

**Comment by RoudiBoy** [comment]
Hi,

Thanks for your answer.

I only use Wavemon for monitoring. In parallel, I have a bash script which log data every 1 seconde.
The fact is even with the iw command, I can't find the dropped packets and lost packets told by Wavemon.
When I do a "iw wlan0 station dump", the command returns nothing but if I do a "iw wlan0 info", I have some information about the network (SSID, type, channel, etc). The problem is I can't find the number of packets dropped or lost. 

Can you tell me with which exact command you can get the number of dropped and lost packets please ?

I am sorry to disturb you, I know you are not responsible for that but I can't find the answer anywhere, despite a lot of researches.

Thanks.

Sincerely

**Comment by RoudiBoy** [comment]
The problem is when I do a `iw dev wlan0 station dump`, the command returns nothing. I tried the `iw phy wlan0 info` but it doesn't show the packets lost or dropped

**Comment by grrtrr** [comment]
You need to be connected to an AP. The number of packets dropped or lost is only reported for an established connection to an access point. The station dump is the same information that wavemon accesses.

**Comment by RoudiBoy** [comment]
Okay, I see the problem now. I have to computers connected each other via WiFi in adhoc mode, so there's no access point.

Thank you very much for your time!

Sincerely
