### ISSUE TITLE
feature request: filter option for scan window

### ISSUE THREAD

**Issue by pvcbe** [uoaerg/wavemon#52]
Hi,
nice utility, I use it regularly, thank you for making and maintaining wavemon. 
Would it be possible to create a filter option for the scan window?
where you can select: 
* ssid (regex?) / bssid
* encryption
* band/frequency
* minimal signal strength

similar to:
https://play.google.com/store/apps/details?id=com.vrem.wifianalyzer

example of android app:
![example](https://lh3.googleusercontent.com/s_NIfcmA3EAHkOtjJBYb05Na6xJY5SbQYLCSHoG392ECS9EdbxW8YVlH-o-6LFYJhLdN=w1920-h1086)

**Comment by grrtrr** [comment]
Thanks for the suggestion. wavemon is a nearly 17 year old program which is currently in maintenance mode.

The scan screen can arguably be improved. It lacks scrolling as for instance is available in htop. This also has searching filtering.

All of this would add a lot of code and require a lot of testing. I am lacking the time to do this, would consider pull requests if they are to a good standard.
