### ISSUE TITLE
wavemon validating

### ISSUE THREAD

**Issue by sahar70** [uoaerg/wavemon#53]
Hi
why Wavemon shows different valus of RSSI? i need ro know RSSI in varied distances of my access point. 
i measure in indoor place. how i can trust to  RSSI given by Wavemon? 
is there any standard conditions for measuring by wavemon?

**Comment by grrtrr** [comment]
There are 2 metrics for the signal quality:
- [_relative received signal strength_](https://en.wikipedia.org/wiki/Received_signal_strength_indication#In_802.11_implementations), shown as _"Link Quality". This is scaled from 0..100%. The actual units are _arbitrary_, many cards use 0..70.
- _power level_ in decibels referenced to 1 milliwatt ([dBm](https://en.wikipedia.org/wiki/DBm).

The values on the info screen and the history screen are the same. It is what the kernel driver reports.
