### ISSUE TITLE
how can i get the formula of Link Quality?

### ISSUE THREAD

**Issue by jimoful** [uoaerg/wavemon#55]
tks for give me answers

**Comment by grrtrr** [comment]
There is not really a formula. Link quality is just a value. Most drivers report between 0 .. 70, some between 0..100.

**Comment by jimoful** [comment]
> There is not really a formula. Link quality is just a value. Most drivers report between 0 .. 70, some between 0..100.

link quality is an aggregate value，it will be calculated in drivers，or it is a physical value？

**Comment by grrtrr** [comment]
Sorry this is the wrong place to ask. You could try linux kernel mailing list or a list for the kernel drivers.
