### ISSUE TITLE
Noise level unknown

### ISSUE THREAD

**Issue by antelk** [uoaerg/wavemon#58]
Dear friends @ wavemon,

I work on project that requires signal levels with noise levels for datasets I am creating.
I tried to use > iw dev [interface_name] survey dump but command output returns nothing.

I also tried wavemon as possible solution but it seems to have problems when it comes to noise levels and s-n ratio:
![image](https://user-images.githubusercontent.com/31781651/49870239-15e59000-fe13-11e8-8f34-817df96a952c.png)

The only noise related data I can find is written in /proc/net/wireless which I doubt is a valid value (always shows -256dBm).

So my question is - is there any way (with or without wavemon) to get signal noise values?

Thank you in advance!
Best,
Ante

**Comment by grrtrr** [comment]
Hi Ante, unfortunately this depends on the card that you are using. Many cards do no longer report noise levels, in these cases the noise level is at the "zero" value (-256dBm).
I have had good success with some of the Atheros cards that do report noise values. For a laptop a replacement card does not cost that much. I have not tested external adapters, might require a little bit of googling to find one
that reports noise levels.

**Comment by antelk** [comment]
Thank you very much. You confirmed what I thought. 

I presume same applies to RPI?

**Comment by grrtrr** [comment]
Yes, very likely.
