### ISSUE TITLE
on_exit is not portable

### ISSUE THREAD

**Issue by joerg-krause** [uoaerg/wavemon#62]
Since commit 4a160b112de6a00739ab597ccd12b98866c006ee wavemon uses `on_exit()`, which is not portable and not available on the C libraries musl and uClibc. According to the [Linux kernel man page](http://man7.org/linux/man-pages/man3/on_exit.3.html) : _Portable application should avoid this function, and use the standard atexit(3) instead._

**Comment by grrtrr** [comment]
Thank you for keeping an eye on portability. Will fix this as soon as possible.
