### ISSUE TITLE
Uninitialized variable in info_scr.c (display_levels()).

### ISSUE THREAD

**Issue by textbrowser** [uoaerg/wavemon#64]
The variable sig_qual_max should be initialized as the following conditions may not be true.

```
	if (linkstat.data.bss_signal_qual) {
		/* BSS_SIGNAL_UNSPEC is scaled 0..100 */
		sig_qual     = linkstat.data.bss_signal_qual;
		sig_qual_max = 100;
	} else if (sig_level) {
		if (sig_level < -110)
			sig_qual = 0;
		else if (sig_level > -40)
			sig_qual = 70;
		else
			sig_qual = sig_level + 110;
		sig_qual_max = 70;
	}
````

**Comment by grrtrr** [comment]
Thank you. The logic avoids using sig_qual_max if sig_qual has not been set (-1), but I will initialize it none the less.

**Comment by textbrowser** [comment]
Sorry to bother you again. The variable should be initialized to a non-zero value so as to avoid an unlikely division by zero.

**Comment by grrtrr** [comment]
`sig_qual_max > 0` iff `sig_qual > -1`. It is not supposed to be used when `sig_qual == -1`.

**Comment by textbrowser** [comment]
OK. :)
