### ISSUE TITLE
Feature request: Show public IP

### ISSUE THREAD

**Issue by victorhck** [uoaerg/wavemon#65]
Hello.
Maybe would be useful to show the public IP besides the local IP.
Greetings.
PS: Thanks for your time and code! :+1:

**Comment by grrtrr** [comment]
I am not sure this is useful. Do you mean an outgoing request like
```bash
>  wget -qO - icanhazip.com
```
For that it is almost better to have _external tools_ (like, e.g. `wget`), since it involves an http client, handling errors from network/routing.
`wavemon` does not have much support for the networking layer, it is a layer 2 tool.

**Comment by victorhck** [comment]
Ok. Then I close the issue.
Greetings
