### ISSUE TITLE
Problem reducing numerical values in Preferences page

### ISSUE THREAD

**Issue by MrEngman** [uoaerg/wavemon#66]
Found wavemon a couple of days ago and I'm trying to get used to using it but seem to have a problem.

I am using it on a Raspberry Pi. I have 2 wifi interfaces and connect to the Pi using one of the wifi interfaces and SSH. The second wifi I am trying to use in monitor mode.

My current issue is with the Preferences page. I was playing around seeing what the various settings were and changed the Statistics updates setting and it is now set at 4000ms and I am now unable to reduce is back to the original value, which I believe was 100ms.

This appears to be an issue with all the settings that use a numerical value. I can increase the value using the right arrow key but I am unable to reduce it back to its original value using the left arrow key.

Using the left and right arrow keys appear to work alright on all non-numerical setting.As an example on the interface setting if it is set to wlan0 using the right arrow key will change it to wlan1 and the left arrow key will change it back from wlan1 to wlan0.

Am I doing something stupid or is there an issue with reducing the settings that use a numeric value.

![wavemon](https://user-images.githubusercontent.com/4400988/71131246-0bab5e00-21ec-11ea-8b05-5c2e0ae8f592.png)

**Comment by grrtrr** [comment]
Hi thanks for reporting. Very interesting problem, not reproducible on `x86_64`. The keys work, so it is unlikely a `$TERM` problem. 

I suspect an untested condition that happens on 32bit. There are comparisons between `int` and `double`, that may be the clue.

If you can give me a couple of days and are able to build from `master`, would you be ok to test that?

**Comment by MrEngman** [comment]
Certain can give it a go. Let me know when it's done and I'll see what I can do.

**Comment by grrtrr** [comment]
I have unified the use of variables. If the problem was caused by mixed types, this should fix it. Could you give this a try please?

**Comment by MrEngman** [comment]
Looks like it is now fixed. I can change the numerical values up and now down OK.

**Comment by grrtrr** [comment]
Thank you very much. I will put out a new release within the next week or two.
