### ISSUE TITLE
Feature Request: Support for USB Wireless Network Adapters

### ISSUE THREAD

**Issue by algent-al** [uoaerg/wavemon#67]
I use a PC using a wireless adapter: 
`Device-2: Realtek RTL8188EUS 802.11n Wireless Network Adapter type: USB driver: r8188eu`
Installed wavemon in my system Solus Budgie 4.

Running `sudo wavemon` and press F3 i get:
`Scan trigger failed on wlp0s26f7u3: No such device `.
I assume that this tool works only for laptops. Is it possible to make it work on PC with adapters too.

**Comment by grrtrr** [comment]
This is very likely due to a restricted kernel driver. 

To _trouble-shoot_ this, refer to the [older troubleshoot steps](https://github.com/uoaerg/wavemon/issues/13#issuecomment-172700883):
- can the interface be attached to an access point (e.g. `iwconfig wlp0s26f7u3 <essid>`), or
- does `iwlist wlp0s26f7u3 scan` or `iw dev wlp0s26f7u3 scan` produce any results?

If the answer to either question is 'no', it could be a driver or firmware problem.

**Comment by algent-al** [comment]
OK here are the outputs of 3 commands:
```
$ iwconfig wlp0s26f7u3
wlp0s26f7u3  IEEE 802.11bgn  ESSID:"RUDI"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.412 GHz  Access Point: 20:F1:7C:6C:4F:DC   
          Bit Rate:65 Mb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=99/100  Signal level=60/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
```
$ iwlist wlp0s26f7u3 scan
wlp0s26f7u3  Scan completed :
          Cell 01 - Address: 20:F1:7C:6C:4F:DC
                    ESSID:"RUDI"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.412 GHz (Channel 1)
                    Encryption key:on
                    Bit Rates:130 Mb/s
                    Extra:wpa_ie=dd1a0050f20101000050f20202000050f2020050f20401000050f202
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    Extra:rsn_ie=30180100000fac020200000fac02000fac040100000fac020000
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    Quality=97/100  Signal level=59/100  
          Cell 02 - Address: 74:EA:3A:D9:19:60
                    ESSID:"wireles"
                    Protocol:IEEE 802.11bg
                    Mode:Master
                    Frequency:2.462 GHz (Channel 11)
                    Encryption key:on
                    Bit Rates:54 Mb/s
                    Extra:wpa_ie=dd1a0050f20101000050f20202000050f2020050f20401000050f202
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    Extra:rsn_ie=30180100000fac020200000fac02000fac040100000fac020100
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                       Preauthentication Supported
                    Quality=0/100  Signal level=70/100  
```
```
$ iw dev wlp0s26f7u3 scan
command failed: Operation not permitted (-1)
```

**Comment by grrtrr** [comment]
Thank you for the output. Could you repeat the `iw dev ... scan` command with a pre-pended `sudo`?

The scan command requires CAP_NET_ADMIN (= root) permissions.

The whole point of this test is to find out the degree of nl80211 support. The `iwlist / iwconfig` commands are the oldest existing wireless commands and rely on the deprecated wireless extensions (wext).

The modern variant that replaces wext is netlink (nl80211), but it is not supported by all kernel drivers.

**Comment by algent-al** [comment]
There is no difference. Updated also `iw` to version 5.4.
```
$ sudo iw dev wlp0s26f7u3 scan
command failed: No such device (-19)
```

**Comment by grrtrr** [comment]
There _is_ a difference. Please compare the error messages.

It is now returning `ENODEV`. The `iw` device, as explained above, uses nl80211 (as does wavemon). The `r8188eu` driver does not support this interface, and so returns an error
to userspace.

Hence you get
- `Scan trigger failed on wlp0s26f7u3: No such device ` in wavemon and
- `command failed: No such device` in iw.

Note that in both cases the same error is returned.

Problem is not in wavemon. You can look into
- using a different device/driver,
- asking the r8188eu maintainer to add nl80211 functionality.
