### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by MagicMuscleMan** [uoaerg/wavemon#68]
Thanks for this useful program.

It would be cool if it had a [spectrum/channel view](https://a.fsdn.com/con/app/proj/linssid/screenshots/channels.jpg/max/max/1) like linSSID. This shows conflicting channels more easily, as it combines channel base frequency and channel frequency width.

This might either be a separate plot (F4?) or put at the lower half of the scan plot in F3.

**Comment by grrtrr** [comment]
Thanks for the suggestion. I am not going to develop it, but will consider good-quality pull requests.

**Comment by MagicMuscleMan** [comment]
Thanks, that's fair enough. Unfortunately, I probably won't find time to get used to the code base and provide the patch.

So I am okay that this request is closed. If I am severely annoyed of missing this feature in the future and therefore change priorities to provide a patch, we can still reopen it.

Thanks again for providing wavemon!

**Comment by grrtrr** [comment]
Thank you for your understanding.
