### ISSUE TITLE
Requires CAP_NET_ADMIN permissions -> Segmentation fault

### ISSUE THREAD

**Issue by StavroMuellerBeta** [uoaerg/wavemon#71]
When running wavemon as a normal user, I do not have the permissions to perform a scan. Wavemon tells me this 'This screen requires CAP_NET_ADMIN permissions' when I press f3. However, pressing any other key after that will throw a segfault. I manged to reproduce this with the latest source build from here and also with the version from my distro's repositories (void linux). I have not changed any wavemon preferences nor created a configuration file.
Dmesg output:
```
[ 4490.639466] wavemon[12421]: segfault at 7fb3507d7b64 ip 00007fb3508dd65f sp 00007ffcc22c8320 error 6 in libc.so[7fb350889000+63000]
```
Screenshot:
![segfault](https://user-images.githubusercontent.com/49550853/86495195-37e59100-bd70-11ea-895c-a77e5f9e9918.png)

**Comment by StavroMuellerBeta** [comment]
I think I have fixed this in my pull request.

**Comment by grrtrr** [comment]
Thank you, I will merge that later.
