### ISSUE TITLE
level history / preference settings

### ISSUE THREAD

**Issue by Norbert-22** [uoaerg/wavemon#74]
Hi, 
 
Hopefully I have not made any dumb mistake...
Have tried to find some similar reports herein but not successful.
 
I installed wavemon version 0.8.2 on a raspberrry 3 stretch system. System was previously updated and upgraded. 
 
The wavemon program is working fine and showing the respective measurements. 
 
But: 
 
item 1 level history
The signal strength histogram is ok
But there is no data for ns level and signal to noise ratio. For both only the status unknown is given in respective brackets.  But in the info screen the signal to noise ratio is given!
(What ns level stands for?) 
 
item 2 
In the preference settings I can increase all the values with figures by using the right arrow. But is impossible to decrease them afterwards with the left arrow. Or any other key.
(In statistics updates upon using the left arrow the value jumps up quite high values immediately.) 
On the other hand there is normal toggle operation right / left arrow possible for all on/off selections possible. 
 
What do I do wrong? Or what to do? 
 
REg.
 
Norbert

**Comment by grrtrr** [comment]
Hi Norbert,

1) Most drivers do not report noise level ("ns level"). Some Atheros cards do, but many cards report nothing.
2) Could be a terminal issue. Would also recommend update (0.8.2 is over 2 years old). Have you tried with a different terminal?

Gerrit

**Comment by Norbert-22** [comment]
Hi Gerrit, 

this is what I get when trying to update the program: 

sudo apt-get install wavemon
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
wavemon ist schon die neueste Version (0.8.1-1). 

saying that this is already the newest version! (just translating the important sentence) 
Where and how to get the newer ones? 

Different terminal? Do you mean different computer? Actually I have tried it with raspberry 3 and Raspberry zero.  with different keyboards - German layout

Noise level, ok understood but what means link quality which is shown on the info page? 

Reg.

Norbert

**Comment by grrtrr** [comment]
If you have the setup, you can build from `master` of this repository.

By _terminal_ I mean the _terminal device_ that `wavemon` and your shell is connnected to. You can print it with `tty`. 
Its type is in `echo $TERM`. 

Link quality is just a relative number from 0..100 or 0..70.

Problem has not been reported so far, and I can't reproduce it. There are terminals that _remap_ keycodes, which could
cause problems.

**Comment by Norbert-22** [comment]
Hi Gerrit, 

Have updated the program to 0.9.0
But behavour remains the same. Even when I uninstall the program and then installing it again the "wrong" settings are used again. 
By the way where are the settings stored?

This is what I get:
pi@raspberrypizero4:~ $ tty
/dev/pts/1
pi@raspberrypizero4:~ $ echo $TERM
xterm-256color

Sorry do not understand how it could be a terminal issue if it seems to be related to the keyboard??

link qualtiy: So it is just a calculation based on signal strength? Signal strength of -40dBm would result in 100% link quality? 
Just nicely looking?

REg

Norbert

**Comment by grrtrr** [comment]
Terminal looks ok. Some terminals (such as gnome-terminal) _remap_ keys as 'shortcuts' (e.g. F1).
I always compare against a _simple_ terminal ,such as a plain `xterm`.

Settings are in `~/.wavemonrc`.

**Comment by Norbert-22** [comment]
Hi,

ok, was able to edit the .wavemonrc file to the original values.  

What else should i check??

Reg

**Comment by grrtrr** [comment]
Please _describe_ how this problem occurs. That is,
- how are you connecting to the Raspberry PI (ssh, X-window),
- what equipment / hardware are you using (bluetooth keyboard, USB keyboard, on-screen keyboard etc),
- does the problem occur if you use different hardware?

There isn't enough in this issue in order to produce a fix.

I will close issues that have not enough information to reproduce the problem.

**Comment by Norbert-22** [comment]
1.  with LXterminal 0.3.0 directly connected or with ssh/xrdp and then opening wavemon in lxterminal
2. USB keyboard directly or via xrdp and win7 computer
3. Checked with some different keyboards - no different behaviour

Is this what you are looking for?

reg

Norbert

**Comment by grrtrr** [comment]
Thanks for the above details. I am not able to reproduce the issue.
The only possible cause I can think of is a couple of key translations that existed since 2012 (fabb7e1a32b64b1ffbd1cc941ba8cd5e8a8b2ffb).

If you have access to a compiler, could you try without the following block in `wavemon.c`?
```c
// wavemon.c, line 219ff
                                /*
                                 * Translate vt100 PF1..4 escape sequences sent
                                 * by some X terminals (e.g. aterm) into F1..F4.
                                 */
#if 0 // BEGIN DISABLED
                                switch (key) {
                                case 033:
                                        escape = 1;
                                        break;
                                case 'O':
                                        escape = 2;
                                        break;
                                case 'P' ... 'S':
                                        if (escape == 2)
                                                key = KEY_F(key - 'P' + 1);
                                        /* fall through */
                                default:
                                        escape = 0;
                                }
#endif  // END DISABLED
```

**Comment by grrtrr** [comment]
I have not heard back and am unable to reproduce this issue. Closing ticket.
