### ISSUE TITLE
tx power display value

### ISSUE THREAD

**Issue by Norbert-22** [uoaerg/wavemon#75]
Hi Gerrit, 

I think that the tx power value (+31dBm )given is a little bit too high. And for sure I have not added a power amplifyer.
It seems that the is some misinterpretation of data read from the interface??

Reg

Norbert

hopefully the picture is readable.

![2020-07-25-140644_1920x1080_scrot](https://user-images.githubusercontent.com/66953506/88456955-d900cc80-ce82-11ea-9a95-9ff2aed4c368.png)

**Comment by grrtrr** [comment]
Can you paste the output of
```bash
> iw dev wlan0 info
```
or else the output of `iwconfig` ?

**Comment by Norbert-22** [comment]
pi@raspberrypizero1:~ $ iw dev wlan0 info
Interface wlan0
	ifindex 2
	wdev 0x1
	addr b8:27:eb:ee:30:e1
	ssid Norberts WLAN neu
	type managed
	wiphy 0
	channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz
	txpower 31.00 dBm

pi@raspberrypizero1:~ $ iwconfig
wlan0     IEEE 802.11  ESSID:"Norberts WLAN neu"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 7C:FF:4D:F2:7B:3B   
          Bit Rate=19.5 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=34/70  Signal level=-76 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:37  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

reg

Norbert

**Comment by grrtrr** [comment]
Thank you -- all 3 report the same information

Other people are reporting the same [[1](https://www.raspberrypi.org/forums/viewtopic.php?t=267797), [2](https://www.raspberrypi.org/forums/viewtopic.php?t=247405)].

It is likely a problem of the driver, not a userspace problem.

**Comment by grrtrr** [comment]
Closing this since problem can not be fixed from within `wavemon`.

Issue should be reported to maintaner(s) of the wireless driver that reports this value.
