### ISSUE TITLE
Suggestion -- number keys for function keys

### ISSUE THREAD

**Issue by hymie0** [uoaerg/wavemon#76]
Please consider adding the number keys to stand in for the matching function keys.  For example, 1 for F1, 3 for F3, 0 for F10, etc.

I suspect that this only involves adding some extra `case` options to the `switch` statement around line 240 of `main.c` , but I don't know enough about github to make the change myself.

**Comment by grrtrr** [comment]
Are you on a chromebook?

**Comment by hymie0** [comment]
No, just a regular computer, with Function keys that don't always work.  I know that I can use letters to hit the different screens, but if I know I want (for example) F3, the fact that I need "3" is more obvious than the fact that I need "S".

**Comment by grrtrr** [comment]
The 1-character shortcut keys are the [underlined letters](https://cloud.githubusercontent.com/assets/5132989/8640926/1f8436a0-28c6-11e5-9336-a79fd002c324.png) at the bottom of the page.

They are also listed in the [manpage](http://manpages.ubuntu.com/manpages/xenial/man1/wavemon.1.html).
