### ISSUE TITLE
License - GPLv2+ or GPLv3?

### ISSUE THREAD

**Issue by code1010111** [uoaerg/wavemon#81]
Hey!
README.md talk about GPLv3, but files with source code talk about GPLv2+.
There may be an error in the README.md?

**Comment by grrtrr** [comment]
Which files?

**Comment by code1010111** [comment]
about_scr.c
conf.c
conf_scr.c
error.c
help_scr.c
info_scr.c
iw_if.c
lhist_scr.c
llist.c
scan_scr.c
ui.c
wavemon.c

This files include text:
... 
* wavemon is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
...
