### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by perkelix** [uoaerg/wavemon#83]
On a host that only has an IPv6 address, wavemon shows "ip: n/a" on version 0.9.1.

A mode desirable approach for future version would be:

IPv4: x.x.x.x/yy (tab) IPv6: x:x:x:x:x:x:x:x/yy

**Comment by grrtrr** [comment]
Thank you, I am currently wrapping up v0.9.3 and will look into this after the release.

**Comment by sliddjur** [comment]
@grrtrr borrowing the thread instead of creating a new issue - will 0.9.3 be released in ubuntu repo? (20.04) I still have version 0.8.2 (built Sat Apr  7 18:16:24 UTC 2018)

**Comment by perkelix** [comment]
@sliddjur You'll need to ask Ubuntu developers to pull in the latest release from Debian.
