### ISSUE TITLE
[feature] Display MCS

### ISSUE THREAD

**Issue by stephen304** [uoaerg/wavemon#86]
It would be useful to show the MCS number next to the bitrate (since it can be hard to know what MCS corresponds to a specific bitrate and channel width). For example, I can run `iw dev wlp2s0 link` and see that my rx MCS is 7 and tx MCS is 9.

```
Connected to ... (on wlp2s0)
	SSID: ...
	freq: 5600
	RX: 2989579880 bytes (8111876 packets)
	TX: 481889773 bytes (2623467 packets)
	signal: -61 dBm
	rx bitrate: 720.6 MBit/s 80MHz HE-MCS 7 HE-NSS 2 HE-GI 0 HE-DCM 0
	tx bitrate: 960.7 MBit/s 80MHz HE-MCS 9 HE-NSS 2 HE-GI 0 HE-DCM 0

	bss flags:	short-slot-time
	dtim period:	2
	beacon int:	100

```

**Comment by grrtrr** [comment]
I have just updated the code on `master`. Can you test if that works for you?

**Comment by stephen304** [comment]
That looks great! Thanks!
