### ISSUE TITLE
"make clean" makes wavemon, rather than just clean/rm *.o

### ISSUE THREAD

**Issue by rogerxxxx** [uoaerg/wavemon#93]
configure seems to be adding " tags wavemon" to the "make clean" entry:

clean:
    @$(RM) *.o *~ tags wavemon

--    @$(RM) *.o *~ tags wavemon
++    @$(RM) *.o *~

Not sure if *~ is needed.

**Comment by grrtrr** [comment]
This is intended behaviour.

**Comment by rogerxxxx** [comment]
Shrugs... I always hate when this is done, especially when packaging as some or most package managers call the "make clean" object themselves, then make, resulting in two configure executions.

I'm guessing you do this for git or version control sources, so you're not doing "make clean && ./configure && make", instead only typing "make clean && make"??

Myself, I just had "clean rm *.o" only.
