### ISSUE TITLE
Line wrap on 1280x1024 displays or less

### ISSUE THREAD

**Issue by rogerxxxx** [uoaerg/wavemon#94]
The line wrap or newline tends to obstruct the border of the ncurses vertical line characters on displays  1280x1024 and less.

The last field, "Radio Measure, Spectrum Mgmt" seems to be the cause, hence line is too long for display on one line, and wraps to the second line overwriting the ncurses vertical characters.

When "Radio Measure" is only displayed, the ncurses vertical border characters behave properly.

A workaround, maybe abbreviating Radio Measure == RM, Spectrum Mgmt == SM, on displays smaller than 1280x1024?  And on displays larger than 1280x1024 (or a certain number of chars), use full words?

Personally, I would never know what RM or SM meant, so might need to employ a help pop-up menu, similar to DD-WRT.  ... just some ideas.
![n56_7199-01-reduced](https://user-images.githubusercontent.com/12102230/108112896-c17a7280-7064-11eb-8747-a0fd5d57bd02.jpg)

**Comment by grrtrr** [comment]
One work-around for this is using a _smaller console font_. Here is how it looks in my terminal:
![image](https://user-images.githubusercontent.com/5132989/108286249-fad6df00-7145-11eb-8b92-8da4fc39e689.png)

Ultimately, the _real fix_ for this will be in #69 - which already requires for its implementation to use a _virtual screen_,
in the way that `htop` uses the screen (which allows to scroll up / down + left / right).

This is a lot of work and I don't know when I will find time for that. I will track that work via #69 and so defer to that issue for follow-up.

**Comment by rogerxxxx** [comment]
Understandable.

Sort of knew there wasn't going to be an easy workaround for this, as from memory, I think this issue has been a long outstanding bug.

I realized using a smaller font was a better approach.  I keep switching between 1280x1024 & 1400x1050, due to a lack of system resources and more easily read font.
