### ISSUE TITLE
Write Found Access Points to Log File?

### ISSUE THREAD

**Issue by rogerxxxx** [uoaerg/wavemon#98]
Can we echo (dump/write) the AP (access points) found, one per line within a log file somewhere?  I'm thinking one AP per line date/timestamped entry/line, along with any details within the one line entry.  Probably save the log files to $HOME/.wavemon-date-time.log?

Kismet does this, but negates to log the date/time.  Also dumps to pcap, etc...

I figure, wavemon was initially designed to dump to stdout or log file initially, so the code may already be there and just deactivated/commented-out.  I'm also thinking a simple iw bash script could probably do similar.

This would also work around the current display issues, with displays <= 1280x1024, with truncated AP details being truncated by end of line/display issues.

**Comment by grrtrr** [comment]
A similar functionality had been asked for earlier, in #18 and #34.

I decided not to implement this, since the same can be achieved by using `iw` with a little bit of `bash` scripting.
